version: '3'
services:

  # https://hub.docker.com/_/rabbitmq
  krabbitmq:
    image: rabbitmq:latest
    #ports:
    # - 33306:3306
    #environment:
    tty: true
    stdin_open: true

  knode:
    build:    
      context: "./"
      dockerfile: ./Dockerfile    
    #ports:
    # - 8501:8501
    tty: true
    stdin_open: true
    depends_on:
      - "krabbitmq"